# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/05_methods.base.ipynb.

# %% auto 0
__all__ = ['BaseCFModule', 'ParametricCFModule']

# %% ../../nbs/05_methods.base.ipynb 3
from ..import_essentials import *
from ..datasets import TabularDataModule
from ..train import TrainingConfigs
from copy import deepcopy

# %% ../../nbs/05_methods.base.ipynb 4
class BaseCFModule(ABC):
    cat_arrays = []
    cat_idx = 0

    @property
    @abstractmethod
    def name(self):
        pass

    @abstractmethod
    def generate_cfs(
        self,
        X: jnp.ndarray,
        pred_fn: Callable = None
    ) -> jnp.ndarray:
        pass

    def update_cat_info(self, data_module: TabularDataModule):
        self.cat_arrays = deepcopy(data_module.cat_arrays)
        self.cat_idx = data_module.cat_idx
        self.imutable_idx_list = data_module.imutable_idx_list


# %% ../../nbs/05_methods.base.ipynb 5
class ParametricCFModule(ABC):
    _is_trained: bool = False

    @abstractmethod
    def train(self, t_configs: TrainingConfigs = None): pass

    def _is_module_trained(self):
        return self._is_trained

